### ISSUE TITLE
"https://whatcms.org/?s=" is not working.

### ISSUE THREAD

**Issue by exrienz** [UltimateHackers/Striker#1]
This script wasn't able to search for CMS if it was using the Wordpress or not

**Comment by UltimateHackers** [comment]
Thanks for reporting. This bug is already known to me.
Actually I don't know why but sometimes it fails to detect the CMS.
I will fix it soon, thanks again.

**Comment by exrienz** [comment]
I think can try to refer spaghetti script.. They was able to detect
WordPress CMS 😊

**Comment by UltimateHackers** [comment]
Its supposed to be a CMS detector and it should not focused only on popular CMSs like WordPress and Joomla.
Anyways I will try to find some alternatives and thanks for your suggestion.

**Comment by UltimateHackers** [comment]
[Fixed]
