### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by jiringgot** [UltimateHackers/Striker#10]
Upon running the program, Dns lookups fail with "TypeError: list indices must be integers, not str" at line 158

There was an error getting results

[+] DNS Records
Traceback (most recent call last):
  File "striker.py", line 222, in <module>
    dnsdump(domain)
  File "striker.py", line 158, in dnsdump
    for entry in res['dns_records']['dns']:
TypeError: list indices must be integers, not str

I just cloned down the repository and ran with a python 2.7.13 installation
after getting the requirements

**Comment by UltimateHackers** [comment]
Everything is working perfectly on my machine.
Can you please tell me what website you were targeting?
I know its matter a of privacy but it would be really helpful to troubleshoot this problem.
You can either comment that here or mail me at s0md3v@gmail.com
Basically, Striker uses dnsdumpter.com to retrieve DNS related data so I will check what kind of data it returns for your target.
I will be waiting for your response.
Thanks.

**Comment by UltimateHackers** [comment]
You must enter a domain name, not an IP address.

**Comment by jiringgot** [comment]
I was just testing with example.com if i remember correctly. And thanks.

**Comment by UltimateHackers** [comment]
Works fine on my machine.

**Comment by hktalent** [comment]
me too
