### ISSUE TITLE
Undefined names: nameserver and files

### ISSUE THREAD

**Issue by cclauss** [UltimateHackers/Striker#11]
flake8 testing of https://github.com/UltimateHackers/Striker on Python 2.7.14

$ __time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./plugins/discovery/dnssearch.py:105:31: F821 undefined name 'nameserver'
            self.nameserver = nameserver
                              ^

./plugins/discovery/dnssearch.py:193:31: F821 undefined name 'nameserver'
            self.nameserver = nameserver
                              ^

./plugins/discovery/googleCSE.py:41:71: F821 undefined name 'files'
                     "&start=" + str(self.counter) + "&q=filetype:" + files +"%20site:" + self.word)
                                                                      ^
F821 undefined name 'nameserver'
```

**Comment by ladyleet1337** [comment]
[?] Enter the target: Traceback (most recent call last):
  File "striker.py", line 38, in <module>
    target = raw_input('\033[1;34m[?]\033[1;m Enter the target: ')
EOFError

getting this error.

**Comment by cclauss** [comment]
The first issue is closed but the second and third still exist.

**Comment by UltimateHackers** [comment]
Why we need to name them if the script does what its designed to do without any problems? ;_;

**Comment by cclauss** [comment]
[PEP 20](https://www.python.org/dev/peps/pep-0020/) line 2: ___Explicit is better than implicit.___

The issue is that if this code gets run or modified in a way where these implicit variables are not defined then a NameError is raised at runtime.  Making them explicit makes the code less prone to failure.
* F821 @ http://flake8.pycqa.org/en/latest/user/error-codes.html
* https://lintlyci.github.io/Flake8Rules/rules/F821.html
