### ISSUE TITLE
Hardcoded API key

### ISSUE THREAD

**Issue by vincentcox** [UltimateHackers/Striker#15]
I don't know if it's intended, but you disclosed your API key in the code.
https://github.com/UltimateHackers/Striker/blob/e79af7f91b6dc5e9bc5f93fa38f352b623dd1d3a/striker.py#L109

People can use this API key on shodan to use your credits. 

It's very generous, but it will be abused ultimately.

**Comment by vincentcox** [comment]
I would revoke the API key in your account.

**Comment by UltimateHackers** [comment]
is there anyway to keep this feature without using a hardcoded API key?

**Comment by vincentcox** [comment]
That will be tricky. If you revoke the key, the script will stop running for all users. 
I know that shodan support developers of tools like these. Maybe you can ask them to get a free API key, pinned down for only that feature (honeyscore). So it cannot be misused for other tasks. They will probably ask you for a mention on your readme.md file in return.
If you get a new key, you can change it here on github, and revoke the other key after a few months.
 I asume that the current key is your personal key because if I call the profile API, I get a name in return:
https://api.shodan.io/account/profile?key=C23OXE0bVMrul2YeqcL7zxb6jZ4pj2by). 
I also see that you  have 0 credits left, so someone else might already be using your account with the key.

**Comment by UltimateHackers** [comment]
Its been 3 days since I sent them a mail and there's still no reply from the Shodan team.

**Comment by vincentcox** [comment]
If there is an UltimateHackeres twitter handle, I would use that to tweet at them (or send a private message). Strange that they didn't replied yet...

**Comment by UltimateHackers** [comment]
They aren't replying so I think I should close this issue now.
Thanks for letting me know about this.
