### ISSUE TITLE
error running striker.py

### ISSUE THREAD

**Issue by sashank** [UltimateHackers/Striker#16]
getting below error , any help ? 
`python3 striker.py 
File "striker.py", line 37
    \/                     \/    \/\033[1;m'''
                                             ^
SyntaxError: Missing parentheses in call to 'print'
`

**Comment by UltimateHackers** [comment]
Striker isn't python3 compatible. You have to run with python2 interpreter

**Comment by UltimateHackers** [comment]
Are you sure that you have installed **mechanize** python library?

**Comment by sashank** [comment]
ok, now working thanks a lot !
