### ISSUE TITLE
error，add try/except

### ISSUE THREAD

**Issue by LowerCode** [UltimateHackers/Striker#23]
HTTP: 
Microsoft-IIS/7.0
Title: 
Stock Brokers
HTTPS: 
Microsoft-IIS/7.0

raceback (most recent call last):
  File "striker.py", line 222, in <module>
    dnsdump(domain)
  File "striker.py", line 156, in dnsdump
    res = DNSDumpsterAPI(False).search(domain)
  File "/root/PenTestTools/Striker/plugins/DNSDumpsterAPI.py", line 92, in search
    res['dns_records']['dns'] = self.retrieve_results(tables[0])
  File "/root/PenTestTools/Striker/plugins/DNSDumpsterAPI.py", line 33, in retrieve_results
    ip = re.findall(pattern_ip, tds[1].text)[0]

**Comment by UltimateHackers** [comment]
Can you please provide me the exact URL you entered?
If you have privacy concerns, you can mail me at: s0md3v@gmail.com

**Comment by LowerCode** [comment]
Ok, I sent mail to to you, please check!

**Comment by UltimateHackers** [comment]
Sorry, Striker isn't compatible with IP addresses. Try entering a domain name.

**Comment by LowerCode** [comment]
i see!

**Comment by thehappydinoa** [comment]
@UltimateHackers you should build in an error handler for this
