### ISSUE TITLE
It can not detect the Drupal cms

### ISSUE THREAD

**Issue by wilbyang** [UltimateHackers/Striker#28]

**Comment by thehappydinoa** [comment]
Please provide the version of Drupal and slightly more information.

**Comment by UltimateHackers** [comment]
It would be very helpful if you can share the target.
If you have privacy concerns, you can share it privately with me at s0md3v@gmail.com

**Comment by wilbyang** [comment]
I run python striker.py using drupal.org as the target. But it says drupal.org doesn't seem to use a CMS.  But drupal.org is obviously using Drupal, which is a very famous CMS/CMF

**Comment by UltimateHackers** [comment]
The issue has been fixed with the latest update.
Thanks for reporting the issue.
