### ISSUE TITLE
ImportError: No module named mechanize

### ISSUE THREAD

**Issue by stanix96** [UltimateHackers/Striker#30]
#Hey, i installed everything like it was explained.

When i start striker.py i get this error:

File "striker.py", line 52
    \/                     \/    \/\033[1;m'''
                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('''\033[1;31m
   _________ __          __ __
  /   _____//  |________|__|  | __ ___________
  \_____  \\\\   __\_  __ \  |  |/ // __ \_  __ \\
  /        \|  |  |  | \/  |    <\  ___/|  | \/
 /_______  /|__|  |__|  |__|__|_ \\\\___  >__|
         \/                     \/    \/\033[1;m''')?

Can somebody help me?

![bildschirmfoto 2018-02-21 um 20 28 40](https://user-images.githubusercontent.com/36637985/36500922-e907f136-1745-11e8-94a3-18fd0de29e23.png)

**Comment by thehappydinoa** [comment]
pip2 install mechanize also this tool is for python 2

**Comment by stanix96** [comment]
![bildschirmfoto 2018-02-21 um 22 36 07](https://user-images.githubusercontent.com/36637985/36506700-af7bdba0-1757-11e8-8ee2-ad4136fc25c2.png)

still getting an error

**Comment by thehappydinoa** [comment]
It must be installed and with sudo...

**Comment by cadesalaberry** [comment]
Or use:

```
pip2 install mechanize --user
```

If you don't want to mess with root.

**Comment by stanix96** [comment]
Ok. Just one stupid question: 

Is this working on Mac? Or only in kali?

**Comment by stanix96** [comment]
ok i fixed everything, close the issue! thank you for your help :)

**Comment by cadesalaberry** [comment]
For the record, how did you fix it?

**Comment by stanix96** [comment]
There was an error that also bs4 and whois weren't imported. So i just fixed it like you said above for the 'mechanize' error:

pip2 install bs4 --user
pip2 install whois --user

**Comment by wadoodqadari** [comment]
How to solve this error "$ python2 firecrack.py
[+] Error: No module named mechanize"
in termux.

**Comment by jair200** [comment]
I get an error when installing cupp 
ImportError: No module named mechanize

**Comment by vanshaj-online** [comment]
> How to solve this error "$ python2 firecrack.py
> [+] Error: No module named mechanize"
> in termux.

I'm getting the same probem bro

**Comment by nickneel9** [comment]
python2 brute.py              
Traceback (most recent call last):
  File "brute.py", line 12, in <module>
    import mechanize
ImportError: No module named mechanize

I'm also getting same error

**Comment by Abdullahi1460** [comment]
[+] Error: No module named mechanize
