### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by oldkingcone** [UltimateHackers/Striker#32]
I have noticed when running this beautiful tool, that if there is no entry within dnsdumpster it just crashes and doesnt complete the tests/runs. The error thrown is a KeyError. Just wanted to bring that to your attention.

**Comment by UltimateHackers** [comment]
Hi there!
Can you please provide more information?
Like the error log or the target itself?
Thanks for reporting.

**Comment by wtf123000** [comment]
Traceback (most recent call last):
  File "./striker.py", line 247, in <module>
    dnsdump(domain)
  File "./striker.py", line 177, in dnsdump
    res = DNSDumpsterAPI(False).search(domain)
  File "/home/fc/Striker/plugins/DNSDumpsterAPI.py", line 93, in search
    res['dns_records']['mx'] = self.retrieve_results(tables[1])
IndexError: list index out of range
fc@rutebox1:~/Striker$

**Comment by oldkingcone** [comment]
That's the one. Sorry have been busy working on a few side projects, have not had time to come back to this.
